/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacienteIdRouteImport } from './routes/paciente.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIdRoute = PacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/gestao' | '/login' | '/paciente/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/gestao' | '/login' | '/paciente/$id'
  id: '__root__' | '/' | '/admin' | '/gestao' | '/login' | '/paciente/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GestaoRoute: typeof GestaoRoute
  LoginRoute: typeof LoginRoute
  PacienteIdRoute: typeof PacienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/$id': {
      id: '/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof PacienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GestaoRoute: GestaoRoute,
  LoginRoute: LoginRoute,
  PacienteIdRoute: PacienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
