// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

// Placeholder values used when env vars are missing. Using a syntactically valid
// JWT for the anon key prevents "Empty token!" from @supabase/auth-js during client
// instantiation — actual network calls will still fail (intentionally), but the
// module loads and the app renders an error state instead of getting stuck.
const PLACEHOLDER_URL = "https://placeholder.supabase.co";
const PLACEHOLDER_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InBsYWNlaG9sZGVyIn0.placeholder";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    // Do NOT throw here: a throw breaks the module's first Proxy access and leaves
    // the AuthProvider stuck on `loading=true` ("Carregando..."). Log loudly and
    // return a placeholder client so the app can render and surface the error.
    console.error(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
        `Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY at BUILD time in the Vercel ` +
        `project (Production, Preview, and Development environments).`,
    );
    return createClient<Database>(PLACEHOLDER_URL, PLACEHOLDER_ANON_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  // Defensive: a malformed session left in localStorage (e.g. an empty access_token
  // from a previous broken deploy) causes "Empty token!" inside @supabase/auth-js.
  // Clear it before instantiating the client.
  if (typeof window !== "undefined") {
    try {
      const storageKey = `sb-${new URL(SUPABASE_URL).hostname.split(".")[0]}-auth-token`;
      const raw = window.localStorage.getItem(storageKey);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (!parsed?.access_token || typeof parsed.access_token !== "string") {
          window.localStorage.removeItem(storageKey);
        }
      }
    } catch {
      // Corrupted JSON — drop everything that looks like a Supabase session.
      try {
        for (let i = window.localStorage.length - 1; i >= 0; i--) {
          const k = window.localStorage.key(i);
          if (k && k.startsWith("sb-") && k.endsWith("-auth-token")) {
            window.localStorage.removeItem(k);
          }
        }
      } catch {
        /* ignore */
      }
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
